### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by vbmade2000**
Update following dependencies.

- nanoid
- env_logger
- sqlx

### CODE REVIEW

**Review by llucax — CHANGES_REQUESTED** [review]
Thanks for the PR! You should run `cargo update` after changing the toml file, so the new dependencies are recorded in the lock file. Then please test the project qt least compiles and runs (I need to add automatic testing yet :-/ ).

**Comment by llucax** [comment]
It 2ould be also nice to state in the commit message the reason for the upgrade (was anything broken? is this just routine maintenance? Is there a new feature you plan to use?).

**Comment by vbmade2000** [comment]
> Thanks for the PR! You should run `cargo update` after changing the toml file, so the new dependencies are recorded in the lock file. Then please test the project qt least compiles and runs (I need to add automatic testing yet :-/ ).

Ok. I thought the **Cargo.lock** file should not be pushed as it is generated from **Cargo.toml**. It compiles successfully.

**Comment by llucax** [comment]
> Ok. I thought the **Cargo.lock** file should not be pushed as it is generated from **Cargo.toml**. It compiles successfully.

Yeah, different approaches can be taken. I prefer to put the lock file because is good to have a snapshot of the dependencies that one is sure they are working. Also for CI is good to know you are testing with the same dependencies locally than in the CI (and the same for deployments). It basically guarantees reproducible builds.

**Review by llucax — APPROVED** [review]
Thanks again!

**Comment by llucax** [comment]
Ah, I protected this branch to require all commits to be signed. I would like to keep that requirement for security reasons, but not bad if it will become an issue for contributors. Would it be too much to ask to sign (`git commit --gpg-sign`) your commits? Again, if you don't have a PGP key and it's too cumbersome to start using it, I'm fine with relaxing this requirement.

**Comment by vbmade2000** [comment]
I don't have a PGP key. I did a few contributions but never came across such a requirement. If possible, relax this restriction.

**Comment by llucax** [comment]
Thanks again!

**Pull request merged**
